name: CI

on:
  push:
    branches:
      - master

permissions:
  contents: write
  id-token: write
  packages: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/elamicon-build:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build:
    runs-on: ubuntu-latest
    needs: build-container
    container:
      image: ghcr.io/${{ github.repository_owner }}/elamicon-build:latest

    steps:
    - uses: actions/checkout@v4

    - name: Make
      run: make build

    - name: Push build directory to build branch
      uses: s0/git-publish-subdir-action@v2.6.0
      env:
        REPO: self
        BRANCH: build
        FOLDER: build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
